build.sh, cfg/system.config.in, src/Builder.hs, src/GHC.hs, src/Oracles/Config/Flag.hs, src/Oracles/Dependencies.hs, src/Oracles/PackageData.hs, src/Package.hs, src/Rules.hs, src/Rules/Compile.hs, src/Rules/Data.hs, src/Rules/Generate.hs, src/Settings/Builders/Ghc.hs, src/Settings/Packages.hs, src/Stage.hs, src/Way.hs
I started to play around with this tonight against the current state of ghc's `master` branch. Here are fixes for a few issues I found.
I eventually stopped when I found that you expect hp2ps and genapply to both have Cabal files. I suspect we can make this happen but I need sleep.
=> Various fixes

src/Base.hs, src/Rules/Actions.hs, src/Rules/Library.hs, src/Rules/Program.hs
And various other simple cleanups.
=> Consolidate box pretty-printing

src/GHC.hs, src/Oracles/ModuleFiles.hs, src/Oracles/PackageDeps.hs, src/Package.hs, src/Rules/Cabal.hs, src/Rules/Documentation.hs, src/Rules/Generate.hs, src/Rules/Library.hs, src/Rules/Program.hs, src/Settings/Builders/Haddock.hs, src/Settings/TargetDirectory.hs
Here is a patch which I've had in waiting. It's still a work-in-progress, but I thought I should at least make its existence know to solicit feedback on the approach.
It does two things,
* Make `PackageName` into a proper type and add a number of associated types (e.g. `PackageId`)
* Make `PackageData` into a typed interface
=> [WIP] Make better use of types

build.sh, src/Main.hs
- Make use of Shake's nice progress report and final statistics
- Lots of quotes for `build.sh`, bash safemode, nice indentation
=> Show Shake statistics, refactor direct Linux build script

src/Settings/Builders/Hsc2Hs.hs
This should fix #35.
To have this fully working, #44 needs to be solved as well.
=> Add "--template" and "-I" arguments to hsc2HsArgs

README.md
add's a link (to what ever systems support `irc://`), everyone else, will hopefully know what to do :)
=> Add IRC to README.md

shaking-up-ghc.cabal, src/Rules/Generate.hs, src/Rules/Generators/GhcVersionH.hs
This should be the final commit to fix #39.
=> Generate includes/ghcversion.h

shaking-up-ghc.cabal, src/Rules/Program.hs, src/Rules/Wrappers/GhcPkg.hs
Adds support for the ghcPkg Wrapper.
=> ghcPkg Wrapper

src/Base.hs
Box minimum size and whether Unicode chars should be used are configurable in the function's body.
New:
```
/---------------------------------\     ╭─────────────────────────────────╮
| Copy file                       |     │ Copy file                       │
|     input: settings             |     │     input: settings             │
| => output: inplace/lib/settings |     │ => output: inplace/lib/settings │
\---------------------------------/     ╰─────────────────────────────────╯
```
Old:
```
/-------------                          ╭─────────────
| Copy file                             │ Copy file
|     input: settings                   │     input: settings
| => output: inplace/lib/settings       │ => output: inplace/lib/settings
\-------------                          ╰───────────── …
```
=> Make output boxes prettier by closing them on the right

src/Rules/Program.hs
=> Wrap ghc-stage2

build.cabal.sh, build.sh
=> Fix readlink for os x.

src/Rules/Actions.hs, src/Rules/IntegerGmp.hs
This improves on #103 and fixes #114, hopefully.
=> Set CONFIG_SHELL, such that libtool obtains the bash header.

.travis.yml
=> Adds osx to the list of operatin systems in the travis.yml

.travis.yml
=> Let's try the stupid --with-gcc fix for os x.

.travis.yml, src/Base.hs, src/Expression.hs, src/GHC.hs, src/Main.hs, src/Predicates.hs, src/Rules.hs, src/Stage.hs, src/Target.hs, src/Way.hs
I tried documenting a couple of low-hanging fruits here.
One thing I could not wrap my head around is documentation of `WayUnit`s fields, I'd appreciate if someone more knowledgeable could have a look at that. `Way` confuses me!
=> Add documentation, small refactorings

src/Base.hs, src/Oracles/LookupInPath.hs, src/Rules/Data.hs, src/Rules/Libffi.hs
- replaces `wordsWhen` with `wordsBy`
- replaces `replace` with `replace`
Fixes #130
=> Use Extra library

shaking-up-ghc.cabal, src/Base.hs, src/Main.hs, src/Oracles/Config/CmdLineFlag.hs, src/Rules/Actions.hs, src/Rules/Library.hs, src/Rules/Program.hs
Adds support for `--build-info` flags as proposed in #134. Also adds our all time favorite unicorn.
=> Add Advanced render box styles

src/Rules/Gmp.hs
This fixes part of issue #159.
=> fix handling of --with-gmp-* configure arguments

.gitignore, build.cabal-new.sh, shaking-up-ghc.cabal
This PR depends on #192 (and includes that commit)
=> Add `cabal new-build`-based wrapper script

doc/windows.md
As per https://github.com/snowleopard/shaking-up-ghc/issues/110#issuecomment-191954062
=> Add docs for how to compile on Windows

src/Builder.hs, src/Predicate.hs, src/Rules/Compile.hs, src/Rules/Dependencies.hs, src/Rules/Gmp.hs, src/Rules/Libffi.hs, src/Rules/Program.hs, src/Rules/Test.hs, src/Settings/Builders/Cc.hs, src/Settings/Builders/DeriveConstants.hs, src/Settings/Builders/Ghc.hs, src/Settings/Builders/GhcCabal.hs, src/Settings/Builders/Hsc2Hs.hs
I haven't completed a full build with this change yet, but the CI bots should pick up the PR .
=> Split CompilerMode for GHC and CC

build.cabal.sh, cabal.project, hadrian.cabal
=> Use in-tree cabal in build.cabal.sh

src/Settings/Default.hs
Part of https://github.com/snowleopard/hadrian/issues/296
=> Disable some warnings

src/Settings/Builders/Cc.hs, src/Settings/Default.hs, src/Settings/Packages/GhcPrim.hs, src/Settings/Packages/Rts.hs
Related: https://github.com/snowleopard/hadrian/issues/296
=> Add Werror to CC and HC

src/Settings/Packages/GhcCabal.hs
Part of https://github.com/snowleopard/hadrian/pull/312, which can fix the version number in `setup-config`'s header section
=> Fix CABAL_VERSION argument in building ghc-cabal

cfg/system.config.in, src/Oracles/Config/Setting.hs, src/Oracles/Path.hs, src/Rules/Wrappers.hs, src/Settings/Builders/GhcCabal.hs, src/Util.hs
These are the result of an attempt to build GHC with Hadrian on FreeBSD on amd64. This resolves #330.
=> Various portability fixes

src/Oracles/Dependencies.hs, src/Rules.hs, src/Rules/Install.hs, src/Settings.hs, src/UserSettings.hs
=> Add Stage1Only rule

src/Rules/Install.hs
Verified that with this change, https://github.com/snowleopard/hadrian/issues/323 can be resolved. But this is still a HACK because of https://github.com/snowleopard/hadrian/issues/318.
=> Fix double copy

src/GHC.hs, src/Rules/Program.hs, src/Rules/Wrappers.hs, src/Settings.hs, src/Settings/Path.hs
Fixes https://github.com/snowleopard/hadrian/issues/105.
verified with:
```
inplace/bin/ghc-stage2 -fexternal-interpreter --interactive
```
=> Add ghc-iserv wrapper

.travis.yml
=> Make OS X build faster and Add GHC 8.0.2 build on Travis CI

src/Rules.hs, src/Rules/Generate.hs, src/Rules/Program.hs, src/Rules/Test.hs, src/Settings/Builders/GhcCabal.hs, src/Settings/Builders/Hsc2Hs.hs, src/Settings/Path.hs, src/Util.hs
This should fix https://github.com/snowleopard/hadrian/issues/359.
=> Fix builder dependencies on generated files

src/Rules/Test.hs
Addresses https://github.com/snowleopard/hadrian/issues/366
=> Fix validate's executable dependency

hadrian.cabal, src/GHC.hs, src/Oracles/Flag.hs, src/Settings.hs, src/Settings/Builders/Common.hs, src/Settings/Flavours/Development.hs, src/Settings/Flavours/Performance.hs, src/Settings/Flavours/Profiled.hs, src/Settings/Flavours/Quick.hs, src/Settings/Flavours/QuickCross.hs, src/Settings/Flavours/Quickest.hs, src/Settings/Packages/Compiler.hs, src/Settings/Packages/Ghc.hs, src/Settings/Packages/GhcPkg.hs, src/Settings/Packages/Haskeline.hs, src/UserSettings.hs
Tested with a more complex example https://gist.github.com/izgzhen/a2d03c333afdb90d3504e127b35f66da
=> Refine cross-compilation implementation

cfg/system.config.in, src/Oracles/Flag.hs, src/Settings/Packages/Rts.hs
solve https://github.com/snowleopard/hadrian/issues/406
=> Complete RTS compiler args

src/Rules/Documentation.hs, src/Settings/Builders/Sphinx.hs
=> Build man page

src/Rules/Documentation.hs, src/Rules/Install.hs
=> Implement install_docs

README.md, src/CommandLine.hs, src/Flavour.hs, src/GHC.hs, src/Rules.hs, src/Settings/Default.hs, src/Settings/Flavours/Development.hs, src/Settings/Flavours/Performance.hs, src/Settings/Flavours/Profiled.hs, src/Settings/Flavours/Quick.hs, src/Settings/Flavours/QuickCross.hs, src/Settings/Flavours/Quickest.hs
=> Finalise documentation build rule

cfg/system.config.in, hadrian.cabal, src/Oracles/Flag.hs, src/Rules/Compile.hs, src/Rules/Generate.hs, src/Settings.hs, src/Settings/Builders/Cc.hs, src/Settings/Builders/Ghc.hs, src/Settings/Default.hs, src/Settings/Packages/Base.hs, src/Settings/Packages/GhcCabal.hs, src/Settings/Packages/Rts.hs, src/Settings/Warnings.hs
See #296
(More commits to come.)
=> Finalise warnings-related arguments

.travis.yml, appveyor.yml, circle.yml
=> Fix CI scripts

cabal.project, src/Settings/Packages/GhcCabal.hs, stack.yaml
=> Fix ghc-cabal build

.travis.yml, README.md, appveyor.yml, circle.yml, doc/cross-compile.md, src/CommandLine.hs, src/Rules/Configure.hs
=> Do not run configure by default

src/Rules/Compile.hs, src/Rules/Dependencies.hs, src/Settings/Builders/Ghc.hs, src/Settings/Packages/GhcCabal.hs, src/Utilities.hs
=> Fix dependencies

src/Rules/Program.hs, src/Settings/Warnings.hs
=> Follow GHC changes

src/Settings/Builders/Cc.hs, src/Settings/Builders/Common.hs, src/Settings/Packages/Rts.hs, src/Settings/Warnings.hs
=> Drop -Werror

src/Rules/Documentation.hs, src/Rules/Generate.hs
Fix #492 and then attempt https://phabricator.haskell.org/D4365.
=> Fix Haddock

doc/user-settings.md, src/Rules/Compile.hs, src/Rules/Generate.hs, src/Rules/Library.hs, src/Rules/PackageData.hs, src/Settings/Builders/RunTest.hs, src/Settings/Packages/Rts.hs
See https://phabricator.haskell.org/D3237
=> Drop custom logic for Scav_thr and Evac_thr

src/Base.hs, src/Builder.hs, src/GHC.hs, src/Hadrian/Builder.hs, src/Rules/Documentation.hs, src/Rules/Install.hs, src/Rules/Test.hs, src/Settings/Builders/Ghc.hs, src/Settings/Builders/Hsc2Hs.hs, src/Settings/Builders/RunTest.hs
An attempt to make dependencies more precise, getting rid of a couple of hacks.
=> Add support for runtime dependencies

src/GHC.hs
See https://phabricator.haskell.org/D4377
=> Add iserv library

src/Settings/Builders/Haddock.hs
Also reorder other flags as in the Make build system
See https://phabricator.haskell.org/D4365
=> Add --quickjump to Haddock

src/GHC.hs
See #504 and https://phabricator.haskell.org/D4377
=> Undo iserv changes

hadrian.cabal, shell.nix
This will make builds more reproducible and also fixes the hadrian build.
=> Pin nixpkgs and all-cabal-hashes in shell.nix

build.sh, hadrian.cabal, stack.yaml
=> Drop the no longer necessary chmod

hadrian.cabal
=> Bump Cabal version

src/Settings/Builders/GhcCabal.hs
=> Add extra include paths when invoking ghc-cabal

src/Builder.hs, src/Builder.hs-boot, src/Rules/Register.hs, src/Settings/Builders/GhcPkg.hs
=> Unregister stage0 package first if it needs to be cloned

README.md, cfg/system.config.in, hadrian.cabal, src/Builder.hs, src/Builder.hs-boot, src/Rules.hs, src/Rules/SourceDist.hs
Reverts snowleopard/hadrian#555
@alpmestan Something is wrong -- have you forgot to check in `BinaryDist.hs`? I'm reverting your commit for now.
=> Revert "Preliminary bindist rule"

src/Hadrian/Haskell/Cabal/Parse.hs, src/Rules/Generate.hs, src/Rules/Register.hs
=> Fix copying of fs*.h files during RTS registration

src/GHC.hs, src/Rules/Program.hs
=> Fix the path to touchy

src/Context.hs, src/Hadrian/Oracles/TextFile.hs, src/Rules/Library.hs, src/Utilities.hs
=> Fix missing libHSghc-8.5-0.a

src/Rules/Register.hs
See https://github.com/snowleopard/hadrian/issues/569
=> Fix lint error

appveyor.yml, src/Rules/Configure.hs
=> Fix AppVeyor

build.global-db.bat
Just copied from hadrian.cabal
=> Add all the default-on extensions to build.global-db.bat

src/GHC.hs, src/GHC/Packages.hs, src/Rules.hs, src/Rules/Program.hs, src/Rules/Test.hs
=> Add checkPpr package and infrastructure for testsuite packages

src/Settings/Builders/Make.hs
This should fix the issues we've been talking about in #599. Let's see what CI says.
=> remove (unnecessary) recursive dependency involving ghcPath

src/Settings/Packages/Rts.hs
=> Update RTS flags

src/Rules/BinaryDist.hs
The code is working on linux now.
@angeman @alpmestan @snowleopard
=> Added featues to binary distribution

src/Context.hs, src/Rules/BinaryDist.hs
Adding includes directory to binary distribution.
We ship include folder in rts directory with binary distrbution.
@alpmestan Is this approach correct?
=> Added includes to Bindist

.travis.yml, appveyor.yml, circle.yml, src/Settings/Packages.hs
@snowleopard There we go. Only Circle CI doesn't save the current dir accross different commands of the script, right?
=> use @quasicomputational's Cabal branch in CI for the time being

src/Hadrian/Utilities.hs, src/Oracles/TestSettings.hs, src/Settings/Builders/RunTest.hs
=> Fix warnings, improve comments and error handling, minor refactoring

src/Expression.hs, src/Hadrian/Haskell/Cabal.hs, src/Hadrian/Oracles/TextFile.hs, src/Rules/Library.hs, src/Rules/Selftest.hs, src/Utilities.hs
=> Fix package dependencies

src/Builder.hs, src/Rules/Documentation.hs
See #664.
I still have some issues locally, but this seems to be related to my LaTeX setup.
=> Fix documentation rules

.travis.yml, circle.yml
I'm hoping to see the OS X travis job go green... =)
=> .travis.yml: update OS X script to test a GHC patch for #614
