snowleopard/hadrian

.gitignore, README.md, build.cabal.sh, shaking-up-ghc.cabal
Add a Cabal and sandbox based way to execute the build system.
Due to problems with Stack bringing its own libraries, I wasn't able to use it to successfully run the GHC build system yet.
=> Add Cabal sandboxed build script

README.md, src/Rules/Dependencies.hs
1fcb025 added includes to the dependencies for the `compiler` package, but `hp2ps` already requires them and is built prior to the `compiler` package. This should fix #48 for good.
Also updates the README.md to reflect the closure of #44.
=> Adds ghcautoconf and ghcplatform as dependencies to hp2ps.

src/Rules/Wrappers/Ghc.hs
the -B option expects "inplace/lib", where takeDirectroy yields: "inplace/lib/bin"
=> Fixes the -B path for the ghcWrapper.

shaking-up-ghc.cabal, src/Main.hs, src/Rules/IntegerGmp.hs
This should fix #71. We build the integer-gmp library similary to libffi now.
This *almost* works. We still need to call
```
./shake-build/build.sh libraries/integer-gmp/gmp/gmp.h
```
as I didn't know where to put the dependency into `integer-gmp` for the `gmp.h`.
And for some reason, we the include path doesn't contain `libraries/integer-gmp/gmp`, even though that's
what I thought
```
includeGmp = ["-I" ++ pkgPath integerGmp -/- "gmp"]
```
would point to.
=> Adds Rules for IntegerGmp

src/Settings/Packages/IntegerGmp.hs
This fixes the isse mentioned in #79, where `gmp.h` could not be found.
=> Adds integer gmp path to the Gcc builder.

src/Rules/IntegerGmp.hs
Fixes the issue mentioned in #83
```
* utils/hpc/stage1/build/tmp/hpc-bin
* libraries/integer-gmp/stage1/build/libHSinteger-gmp-1.0.0.0.a
* getDirectoryFiles  [libraries/integer-gmp/gmp/objs/*.o]
libraries/integer-gmp/gmp/objs: getDirectoryContents: does not exist (No such file or directory)
```
=> Split libgmp.a

.travis.yml, .travis/install-cabal-happy-alex.sh, .travis/install-ghc-shake.sh, .travis/install-ghc.sh, .travis/print-env.sh, .travis/run-ghc-shake.sh, README.md
A rather hacky way to get CI going.
The problem is that Travis clones into a certain directory, but we'd like the Shake build system to be part of a second clone we have to do explicitly (GHC). The script does some dirty tricks to get it done™, but we should probably clean up the attempt a bit in the future.
CI build log: https://travis-ci.org/quchen/shaking-up-ghc
=> Travis CI using dirty tricks

src/Rules/Generate.hs, src/Settings/Packages/Rts.hs
Building rts depends on derived constants, as we can not rely on the compiler to be build prior to rts,
as we build rts with gcc, and hence do not depend on ghc, we need to have rts depend on the derived
constants. This fixes #94. However, if we are going to build rts with the stage1 ghc, this should not be
an issue anymore (see #90), as derived constants would be build then anyway. Yet I do not see any
problem with explicilty noting down the derived constants dependency for rts.
=> Adds derivedConstantsDependencies for rts

shaking-up-ghc.cabal, src/Settings/Args.hs, src/Settings/Packages/IservBin.hs
Fixes #102. But does not *yet* include the generation of the wrapper script.
=> Adds -no-hs-main to iservBin

src/Base.hs
This has been issuing "unnecessary import" warnings for quite some time for me.
=> Fix unnecessary import hiding of "parallel"

.travis.yml
The shallow clone brings down cloning GHC to 10 megs instead of almost 100, giving us a small CI speedup.
(For reasons unknown to me, the Haskell.org Git instance does not support shallow clones.)
=> CI: Shallow clone GHC from Github instead of Haskell.org

.travis.yml
We've reached a somewhat stable level of green-ness on Travis, so I think we can reduce the number of messages to the more relevant ones.
=> Report success on IRC only if the build was fixed

src/Rules/Actions.hs, src/Rules/Libffi.hs
Following on from #156, I think a little more needs to be in the `actionFinally`, so that if things fail while extracting the tarball we still clean up properly.
=> Cleanups in libffi

README.md
It's package name is camel case rather than lowercase (unlike most packages)
=> #155, fix the name of the QuickCheck package

cfg/system.config.in, src/Oracles/Config/Setting.hs, src/Rules/Gmp.hs, src/Settings/Builders/GhcCabal.hs, src/Settings/Builders/Hsc2Hs.hs
@snowleopard this is requested dirs to dir pull request. I'm trying to make it as simple as possible and so putting dir into list whenever applicable to keep code intact. Tested on Solaris 11 with system supplied gmp and ffi libraries.
=> fix "dirs" to "dir" for gmp and iconv libraries

src/Settings/Packages/IntegerGmp.hs
@snowleopard this PR fixes issue of ghc-cabal configuring integer-gmp with intree gmp even when user prefers to use system supplied gmp.
=> do not pass --with-intree-gmp to configure when system gmp is used

.gitignore, build.cabal.sh, build.stack.sh, stack.yaml
I've found stack to be more reliable than cabal sandboxes.
This PR adds `build.stack.sh` based on `build.cabal.sh`
=> Allow building ghc-shake with stack

shaking-up-ghc.cabal
We need this so cabal (this is even more important with the upcoming
nix-style cabal features) can do a proper job so this is a pre-requisite
for the new build-system being used by default for GHC anyway, as we
need to be as accurate as possible with the build specification to give
`git bisect` a chance of remaining usable.
=> Make .cabal meta-data more accurate

stack.yaml
I don't plan to change this file every time there is a new stackage lts, but lts-4.x has a bug with aeson.
=> Update stack.yaml to lts-5.1

build.bat
At the moment if compiling the build script fails the build.bat returns 0, it should return 1 to indicate failure. I checked it still returns 0 on success and 1 on compilation failure.
=> Ensure that if ghc compilation fails then we return a non-zero error code from build.bat

stack.yaml
Since you bumped the lower bound, this is necessary for `stack build` to work.
=> Add shake-0.15.6 to stack extra-deps

src/Rules/Actions.hs
Implementing `moveDirectory` by calling into `renameDirectory` is
problematic because it doesn't work across file-systems (e.g., a
tmpfs based `/tmp`).
This fixes the problem by calling into `mv` instead (similarly to
what we do for `copyDirectory`).
=> Actions: use `mv` instead of renameDirectory (fixes #236)

build.cabal-new.sh, build.cabal.sh, build.sh, build.stack.sh, src/Base.hs
This avoids using colors when the output is, e.g., redirected to a
file. This requried a change to avoid passing the `--colour` flag to
shake (so that hadrian is in charge of colors).
I've also made minor changes to the colors themselves, opting to use
the standard colors (not the bright/vivid ones, otherwise we risk that
for some configurations this will be less readable).
Finally, I've changed the color for `putBuild` - using white
foreground color is problematic (this was not a problem before due to
passing the `--color` flag to shake that was forcing different color).
Signed-off-by: Michal Terepeta <michal.terepeta@gmail.com>
=> Check if the output supports colors (fixes #244)

src/Settings/Builders/Make.hs
GHC testsuite uses the `THREADS` env variable (and not the make's `-j`
setting) to control the parallelism. This commit sets THREADS to the
value of `shakeThreads`.
=> Set `THREADS` when running validate

src/Rules/Data.hs
Recent commit split off the m32 allocator to `rts/linker/`, which
broke the build using Hadrian (since it didn't know about the new
directory). This fixes it.
Signed-off-by: Michal Terepeta <michal.terepeta@gmail.com>
=> Packages/Rts: add `linker` to RTS directories

README.md
This places a note which shows how to mitigate #11744 with Hadrian.
I found it non obvious on which parameter to use with the `Configure` constructor.
=> Note on nm on OS X

hadrian.cabal, src/Oracles/DirectoryContent.hs, src/Rules/Actions.hs, src/Rules/Oracles.hs
These new functions will be helpful when implementing the 'sdist' and
'install' rules.
=> Add actions copyDirectoryContent and runBuilderWith

hadrian.cabal, stack.yaml
This seems to fix using `build.stack.sh` for me (I haven't finished building the whole GHC yet though).
I'm also not sure about the version bound on `Cabal` in the `hadrian.cabal`. What do you think?
=> Change the stack configuration to use the local Cabal lib

src/Rules/Dependencies.hs
There were situations when building concurrently when we would
request `gmp.h` before it had been built (or copied).
This was occuring when we generated the list of dependents for
the c files in the `integer-gmp` folder. Thus, when generating the
dependents for this library we now require `gmp.h`.
=> Fix inability to find gmp.h when building concurrently

src/Rules/Data.hs, src/Rules/Generate.hs
This fixes a TODO to change the `generatedDependencies` to
use `Expr`.
Signed-off-by: Michal Terepeta <michal.terepeta@gmail.com>
=> Make generatedDependencies an Expr [FilePath]

src/Builder.hs, src/Rules/Compile.hs, src/Rules/Generate.hs, src/Settings/Builders/Cc.hs
So this is probably not ready to be merged, but I wanted to discuss a few things :-)
- I'm not sure what we could clean up - I'm planning to have a look at the places that use the current lists of generated files and see whether we can remove some of the explicit calls to `need` in favor of this approach. Ideas are welcome!
- It seems that applying the same trick to `.hs` files might be a bit more complicated - we can try to tell GCC to treat it just as a `.c` or `.h` file and stop at pre-processing, but things like `MIN_VERSION_*` still cause it to die with an error (since they're not defined).
- Does GHC actually have a case where a generated file `#include`s another generated file? (if not we could just go with a bit more brute-force approach of grepping the source?).
- Finally, I'm …
=> Use GCC's `-MM`/`-MG` to find missing dependencies

stack.yaml
Apart from simplifying `stack.yaml`, removing explicit `extra` will also make the upgrade to GHC 8.0 easier (once stackage LTS moves to it).
`extra` is no longer necessary since it's included on stackage:  https://www.stackage.org/lts-6.12/package/extra-1.4.10
I've tested this by building GHC locally.
=> Bump stack to lts-6.12 and remove extra pkg from extra-deps

src/CmdLineFlag.hs
This corresponds to the actual argument names accepted by --flavour which is what most people will be looking for if they run --help.
=> Lowercase flavour names in --help

src/Builder.hs, src/GHC.hs, src/Rules.hs, src/Settings/Default.hs
This addresses GHC #12619, allowing the users guide to be built with only the stage 0 compiler.
Also eliminates some `fromJust`s that I encountered when putting this together.
=> Build mkUserGuidePart with stage-0

doc/windows.md
Added a note about git's default line-ending settings on Windows that can break the build and require starting over with the correct setting.
=> Added a note about git line-ending settings

hadrian.cabal, src/GHC.hs, src/Main.hs, src/Oracles/Config/Setting.hs, src/Rules.hs, src/Rules/Generate.hs, src/Rules/Install.hs, src/Rules/Program.hs, src/Rules/Wrappers.hs, src/Settings.hs, src/Settings/Builders/GhcCabal.hs, src/Settings/Packages/Rts.hs, src/Settings/Path.hs, src/UserSettings.hs
See https://github.com/snowleopard/hadrian/issues/219
=> Add Install Rules

src/Base.hs, src/Rules.hs, src/Rules/Library.hs, src/Settings/Builders/Cc.hs, src/Settings/Builders/Ghc.hs, src/Settings/Default.hs, src/Settings/Flavours/Quick.hs, src/Settings/Flavours/Quickest.hs, src/Way.hs
=> Build dynamic libs

src/Settings/Default.hs
We would previously pass -Werror=unused-but-set-variable and -Wno-error=inline
to ghc, despite the fact that they are gcc flags.
=> Don't pass gcc warning options to ghc

cfg/system.config.in, src/Builder.hs, src/Oracles/Path.hs, src/Rules/Gmp.hs, src/Rules/Libffi.hs, src/Rules/Library.hs, src/Settings/Builders/GhcCabal.hs, src/Util.hs
Previously we would always use the ar of the target; this is incorrect.
Fixes #350.
=> Use correct ar for host/target

hadrian.cabal, src/Settings/Default.hs, src/Settings/Packages/Cabal.hs
The performance of the stage0 `Cabal` build is not critical. I am guessing that this will help bring down the stage0 compilation time, although I have yet to quantify this.
=> Don't optimize cabal stage0 build

.travis.yml
The latest build failure https://travis-ci.org/snowleopard/hadrian/jobs/255299317 is probably caused by this. Adding this line makes the build status list clearer since there is not a non-relavent "Ruby", but I should anticipate that it might introduce some unwanted effects.
=> Drop language in Travis CI config

hadrian.cabal
This brings productivity from roughly 40% to 95%. With parallel GC we generally
spend much of our time synchronizing between the GC threads and relatively
little time doing productive work since we spend most of our time waiting for external processes and generate relatively little garbage.
=> Disable parallel garbage collection

src/Builder.hs, src/Rules/Compile.hs, src/Settings/Builders/Ghc.hs, src/Settings/Default.hs, src/Settings/Packages/Base.hs, src/Settings/Packages/Rts.hs
https://github.com/snowleopard/hadrian/issues/349
=> Use GHC to compile C files

build.bat, build.stack.bat, src/Hadrian/Oracles/ArgsHash.hs, src/Hadrian/Oracles/DirectoryContents.hs, src/Hadrian/Oracles/FileCache.hs, src/Hadrian/Oracles/KeyValue.hs, src/Hadrian/Oracles/Path.hs, src/Hadrian/Utilities.hs, src/Oracles/ModuleFiles.hs
Two things in the patch:
* I cleaned up the `.bat` files - more readable, don't change the directory in the calling shell.
* I added `RuleResult` instances for every oracle, which is required to compile with shake-0.16. I added a compat wrapper for now, but once the new version is released that can be removed.
This patch means the shake release is getting a lot closer.
=> .bat file tidy up plus shake-0.16 compatibility

src/Hadrian/Oracles/DirectoryContents.hs, src/Rules/Install.hs
=> Fix install rules by untracking copy files and use relative path

src/Rules/Install.hs
Fix:
```
Error when running Shake build system:
* install
user error (Development.Shake.cmd, system command failed
Command: inplace/bin/ghc-cabal copy libraries/integer-gmp /tmp/tmpME8BvT/ghc/_build/stage1/libraries/integer-gmp strip /tmp/tmpME8BvT /usr/local /usr/local/lib/ghc-8.3.20170821 /usr/local/share/doc/ghc-8.3.20170821/html/libraries 'v p dyn'
Exit code: 1
Stderr:
ghc-cabal: can't find include file ghc-gmp.h
)
```
http://hadrian-status-dev.zhenzhang.me/logs/2017-08-22T06%3A48%3A13.572819%25default%255631.28768206%25failure.err.log
=> Install rule: copy gmp header

src/Settings/Packages/GhcCabal.hs
This mirrors a change made to GHC in http://git.haskell.org/ghc.git/commit/a28a55211d6fb8d3182b0a9e47656ff9ca8a3766.
=> Remove unnecessary use of -DGENERICS flag

doc/cross-compile.md, hadrian.cabal, src/Oracles/Flag.hs, src/Rules.hs, src/Settings.hs, src/Settings/Builders/Common.hs, src/Settings/Default.hs, src/Settings/Packages/Compiler.hs, src/Settings/Packages/Ghc.hs, src/Settings/Packages/GhcPkg.hs, src/Settings/Packages/Haskeline.hs, src/UserSettings.hs
Tested with arm-linux-gnueabihf using https://gist.github.com/izgzhen/26e49e7bf2e79a9a8f0a3ec37e4837af
=> Add cross compilation

cfg/system.config.in, hadrian.cabal, src/Builder.hs, src/Context.hs, src/Main.hs, src/Rules/Documentation.hs, src/Rules/Gmp.hs, src/Rules/Install.hs, src/Rules/Libffi.hs, src/Rules/SourceDist.hs, src/Rules/Test.hs, src/Settings/Builders/GhcCabal.hs, src/Settings/Builders/Haddock.hs, src/Settings/Builders/Sphinx.hs, src/Settings/Builders/Tar.hs, src/Settings/Builders/Xelatex.hs, src/Settings/Default.hs, src/Settings/Packages/Compiler.hs
Hello,
I am working on [Trac 14144](https://ghc.haskell.org/trac/ghc/ticket/14144). I thought it reasonable to revamp the doc building here rather than in the Make-based system. In short, this patch lets you run:
`$ ./build.cabal.sh --haddock docs`
Which will generate:
```
$ tree -L 2 _build/docs
_build/docs/
├── archives
│   ├── Haddock.html.tar.xz
│   ├── libraries.html.tar.xz
│   └── users_guide.html.tar.xz
├── html
│   ├── Haddock
│   ├── libraries
│   └── users_guide
└── pdfs
├── Haddock.pdf
└── users_guide.pdf
```
Where the `libraries` folder holds haddocks and colored sources.
This is not ready quite yet, as there are a couple sticking points that I could use advice on:
1.) I would like to run the Sphinx or Xelatex builders on documentation "packages", like the users' guide at …
=> Implement documentation building

src/Rules/Generate.hs
simple fix reflecting upstream break change: https://github.com/ghc/ghc/commit/f63bc730c7ea42ca6882f8078eb86be8bf1cc6ad
=> Fix Config.hs to import GhcPrelude

hadrian.cabal
When I added `-qg` to the default RTS options in
57cfa03c23047bb0c731428e97ca716d9a1cf312 (#385) I neglected to consider that it
the -with-rtsopts flag would override the previous flag setting `-I0`. This
had the effect of reenabling idle GC, causing GC time to regress terribly. I
likely didn't notice this since I had passed the flags directly to the `hadrian`
executable with `+RTS` while testing.
Moreover, I mistakenly wrote `-qg0`, which (somewhat confusingly)
actually *enables* parallel GC. Instead I wanted to write `-qg`.
=> Fix usage of -with-rtsopts

build.sh
The previous approach was terribly unreliable, potentially picking up stale executables which lead me to waste an hour debugging #425.
=> build.cabal.sh: Use cabal new-run

cfg/system.config.in, src/Oracles/Flag.hs, src/Settings/Builders/Common.hs, src/Settings/Packages/GhcPrim.hs, src/Settings/Packages/Rts.hs, src/Settings/Warnings.hs
See https://github.com/snowleopard/hadrian/issues/449.
=> Drop GccLtXX flags, require GCC > 4.7 and up

hadrian.cabal
GHC's `master` branch now sits on a snapshot of Cabal 2.1.0.0
=> Widen bounds on Cabal

appveyor.yml
See the end of this log: https://ci.appveyor.com/project/snowleopard/hadrian/build/1.0.788
```
Updating build cache...
Cache 'c:\sr' - Calculating dependencies checksum...Error calculating dependencies CRC for c:\sr: Error calculating CRC32 for c:\new-hadrian\appveyor.yml: The system cannot find the path specified
Build success
```
=> Fix AppVeyor cache failure

src/Settings/Packages/Rts.hs
As pointed out in D4181, these headers refer to undefined macros.
=> hadrian: Disable -Wno-undef in files which include ffi.h

cabal.project
Using a local `filepath` forces `new-build` to build the
non-local build-tool `alex` as in-place which however isn't supported properly
by `cabal new-build` yet (this will be fixed at the earliest in cabal 2.2) and thus
breaks `hadrian/build.sh` for me.
=> Unbreak `cabal new-build`

stack.yaml
=> Do not depend on the in-tree filepath library

build-nix, build.nix.sh, shell.nix
This adds two new files to the hadrian directory
shell.nix sets up the build envrionment you need to build ghc
build-nix is a simple wrapper which invokes hadrian in the correct environment
Note: this patch was authored by @mpickering, however it ended up on phabricator due to the subtree as https://phabricator.haskell.org/D4207.
=> Add ways to build hadrian using nix

shell.nix
This allows you to use configurePhase/buildPhase as usual and
set the right configureFlags rather than end up with a broken
executable.
=> Extend ghcHEAD derivation rather than make a new derivation

cabal.project, stack.yaml
See #481 
Note that we might need to reverse this when we merge `ghc-cabal` into Hadrian (see #445).
=> Drop redundant dependencies on in-tree packages

README.md, circle.yml, doc/user-settings.md, hadrian.cabal, src/Hadrian/Utilities.hs, src/UserSettings.hs
Doing the high-impact work, I have fixed the colored output when running with
`-j` :P This patch also removes `ansi-terminal` as a dependency, which will be
easier to explain in a second.
The root of the issue is that hadrian currently outputs:
```
\ESC[34m<SOME OUTPUT>\n
\ESC[0m
```
with newline character added for emphasis. My brief research suggests `stdout`
is typically line buffered, so the final reset code can break other lines.
If you chase Shake's definition of `putNormal` all the way to
https://github.com/ndmitchell/shake/blob/c9c4246ec6e9d3ca80eabea10d64e01b6c70d094/src/Development/Shake/Internal/Core/Run.hs#L75,
you can see that it uses locks. So if we can combine the color and message
output into a single `putNormal` call, we can drop a fair bit of the logic.
This means we …
=> Fix broken colours with `-j`

hadrian.cabal
As the Cabal 2.2 release branch has been cut, we need to relax the constraint on Cabal in hadrian.
=> Relax Cabal constraint

src/Settings/Packages/GhcCabal.hs
This has been the case since https://github.com/haskell/parsec/commit/89d4541f5cf523cf1fb1dffa43179ac0d1b33431.
=> ghc-cabal: Parsec modules are now found in libraries/parsec/src

shell.nix
- The `ghc821` isn't available anymore, using `ghc822` instead
- Dependencies to the `ghcHEAD` package are now specified as `nativeBuildInputs` rather than `buildInputs`
- `./validate` needs sphinx to be installed
I use this setup (minus the `hadrianPackages.hadrian` line) for building GHC. Using hadrian for the build doesn't work, as `nix` fails to install `shake-0.16` which seems to miss [this fix](https://github.com/ndmitchell/shake/commit/31fa7ce765bebb2acceca9a0dd9234320d36655f). I'm not too familiar with nix, but I had to manually update the cabal-hashes tarball which breaks every time I `nix-channel --update`. Last time I tried, it probably broke somewhere else, so I'm just using this file as a base for building GHC HEAD with `make`.
=> Make shell.nix less broken

shell.nix
`configurePhase` in `nix-shell --pure` was failing without it:
```
[nix-shell:~/Projects/ghc]$ configurePhase
Traceback (most recent call last):
File "./boot", line 193, in <module>
check_for_url_rewrites()
File "./boot", line 29, in check_for_url_rewrites
subprocess.check_output('git config remote.origin.url'.split()).find(b'github.com') != -1 and \
File "/nix/store/dckjl7420jzqkca22r362sx13klpww76-python3-3.6.3/lib/python3.6/subprocess.py", line 336, in check_output
**kwargs).stdout
File "/nix/store/dckjl7420jzqkca22r362sx13klpww76-python3-3.6.3/lib/python3.6/subprocess.py", line 403, in run
with Popen(*popenargs, **kwargs) as process:
File "/nix/store/dckjl7420jzqkca22r362sx13klpww76-python3-3.6.3/lib/python3.6/subprocess.py", line 709, in __init__
restore_signals, start_new_session) …
```
=> Add 'git' to nativeBuildInputs in shell.nix

src/Rules/Clean.hs
Following https://phabricator.haskell.org/D4416 configure will now be copying or hard-linking certain files to a few packages. the Make based system will remove them on clean.
This patch adds the `Hadrian` part.
=> Add clean routines for fs files copied by configure

doc/user-settings.md
See #534 and https://ghc.haskell.org/trac/ghc/ticket/10536
Turns out most of the content I was thinking of was already explained, so I just kept it simple.
cc @snowleopard @izgzhen
=> docs: add user-defined flavour example for turning off dynamic linking

src/Settings/Packages/Rts.hs
Hi,
I'll be landing https://phabricator.haskell.org/D4416 soon but that requires some new build arguments for the `rts` due to Linux. The build will fail without this change.
The flag controls name-mangling of some `I/O` functions. Without it they'll be in the default namespace and the build will fail with an unknown symbol.
Also I noticed `xxhash.c`'s optimization flags were not the same as Make, so I've corrected those.
=> Move rts I/O Functions in different namespace.

src/CommandLine.hs, src/GHC.hs, src/Hadrian/Haskell/Cabal/Parse.hs, src/Rules/Clean.hs, src/Rules/SourceDist.hs, src/Settings/Builders/Common.hs, src/Settings/Builders/GhcCabal.hs, src/Settings/Default.hs
=> Fix warnings

src/Rules/Gmp.hs, src/Rules/Library.hs
Currently both Windows and Linux builds using `integer-gmp` are failing:
```
Error when running Shake build system:
* _build/stage1/lib/package.conf.d/integer-gmp-1.0.2.0.conf
* _build/stage1/libraries/integer-gmp/build/HSinteger-gmp-1.0.2.0.o
* _build/stage1/libraries/integer-gmp/build/gmp/include/ghc-gmp.h
* _build/stage1/libraries/integer-gmp/build/gmp/config.mk
Error, rule failed to build file:
_build/stage1/libraries/integer-gmp/build/gmp/config.mk
CallStack (from HasCallStack):
error, called at src\Development\Shake\Internal\Rules\File.hs:171:58 in shake-0.16-BDmtKOMxPdtLRnDkDJohXq:Development.Shake.Internal.Rules.File
```
=> Fix integer-gmp build

src/Settings/Builders/Common.hs
=> fix missing symbols when cross-compiling

src/GHC.hs
A nicer fix would involve patching GHC to not just look under
$libexec/ but also under the directory where the GHC binary itself lives
(bin/ for hadrian), so that we can leave all binaries under bin/.
Addresses [Trac #15132](https://ghc.haskell.org/trac/ghc/ticket/15132).
Without this patch, this used to fail:
``` sh
$ echo '> main = putStrLn "hello"' > foo.lhs 
$ _build/stage1/bin/ghc foo.lhs
```
with an error saying that ghc could not find `unlit` at `_build/stage1/lib/bin/unlit`, where it expects it. With this patch, GHC successfully compiles that file.
=> Fix unlit by placing it under lib/bin/ instead of bin/

src/Base.hs, src/Rules/Generate.hs, src/Rules/Program.hs
This change updates Hadrian for an upcoming revision to GHC.
For details, see https://phabricator.haskell.org/D4695
=> Add dependency on the new "llvm-passes" file.

src/CommandLine.hs, src/GHC.hs, src/GHC/Packages.hs, src/Hadrian/Utilities.hs, src/Rules/Test.hs, src/Settings/Builders/Make.hs, src/Settings/Builders/RunTest.hs, src/Settings/Default.hs
@snowleopard @angerman 
Validation result after this push: 
SUMMARY for test run started at Mon May 14 00:32:42 2018 IST
0:20:37 spent to go through
6359 total tests, which gave rise to
23523 test cases, of which
17231 were skipped
42 had missing libraries
6098 expected passes
94 expected failures
0 caused framework failures
0 caused framework warnings
1 unexpected passes
55 unexpected failures
2 unexpected stat failures
=> Added support for testsuite

hadrian.cabal, stack.yaml
The shake-0.16 can't be built with ghc-8.4.3, due to the
Semigroup-Monoid-Proposal changes. shake-0.16.1 fixed that.
=> Bump shake version to 0.16.1.

shell.nix
Lifted from: https://github.com/alpmestan/ghc.nix/blob/master/default.nix
I'm not sure why I had to specify `.dev` and `.out`, but this is what worked for me
=> Add `gmp` and `ncurses` as nix dependencies (#615)

src/GHC.hs, src/Hadrian/Haskell/Cabal/PackageData.hs, src/Hadrian/Haskell/Cabal/Parse.hs, src/Oracles/Flag.hs, src/Rules/Generate.hs, src/Rules/Program.hs, src/Settings/Builders/GhcCabal.hs, src/Settings/Builders/Hsc2Hs.hs, src/Settings/Builders/RunTest.hs, src/Settings/Packages.hs, src/Settings/Packages/Compiler.hs, src/Settings/Packages/Rts.hs
While trying to fix the issue #614, I came across this: https://phabricator.haskell.org/D4683
Then I noticed that we currently remove `ldOptions` from RTS. Let's see if we can build with them.
P.S.: The second commit below is the actual change. The first is just some clean up.
=> Minor revision

src/GHC.hs, src/Rules/Test.hs, src/Settings/Builders/RunTest.hs
This patch adds 2 more packages (both required for at least some tests) and tries to set some more test options correctly, using the information we have from the `Flavour`. Feedback welcome! I'm not sure how reliable that is.
=> attempt at setting some more test arguments correctly

src/Hadrian/Haskell/Cabal/PackageData.hs, src/Hadrian/Haskell/Cabal/Parse.hs, src/Oracles/ModuleFiles.hs
Previously, we simply treat file name for `Main` module as `Main.hs` to build executables. That doesn't work for the `timeout` program. This patch fixes the problem.
=> For executables, we should read the `main-is` field from the cabal file.

src/GHC.hs, src/GHC/Packages.hs, src/Rules/Test.hs
Hi, @snowleopard, I'm working on the timeout program in testsuite on windows. I'm trying to build the `testsuite/timeout` using the `buildProgram` rules, just like other utils programs.
I have added the program definition in `GHC.hs`:
~~~haskell
timeout             = hsPrg  "timeout"         `setPath` "testsuite/timeout"
~~~
However I'm lost in the following error message when execute `./hadrian-ghc.sh inplace/bin/timeout.exe`:
~~~
Error when running Shake build system:
* inplace/bin/timeout.exe
* _build/stage0/testsuite/timeout/WinCBindings.o
* _build/stage0/testsuite/timeout/WinCBindings.o _build/stage0/testsuite/timeout/WinCBindings.hi
* OracleQ (KeyValues ("_build/stage0/testsuite/timeout/.dependencies","_build/stage0/testsuite/timeout/WinCBindings.o"))
* …
=> Build timeout program with `buildProgram` rules on windows.

hadrian.cabal, src/GHC.hs, src/Oracles/TestSettings.hs, src/Rules/Test.hs, src/Settings/Builders/Ghc.hs, src/Settings/Builders/GhcCabal.hs, src/Settings/Builders/RunTest.hs
I have copied some files as required by testsuite.
Also, I have unsuccessfully attempted to resolve #626.
@sighingnow @snowleopard @alpmestan
=> Remove validation errors

build.cabal.sh, src/Rules/BinaryDist.hs
Fixes #524 #463
@snowleopard @angerman @izgzhen 
Test: Remove the local cabal sandbox, then run ./build.sh. Stop the process mid-installation, and then run the command again. Setup will start by installing the program where we previously stopped.
=> Fix cabal sandbox init rule

src/GHC.hs, src/Rules/Test.hs, src/Settings/Builders/RunTest.hs
We now avoid building the Haskell timeout program when not on Windows, and fix a problem with the action that produces the Python equivalent on Linux (it was not shipping the .py file along with the shell script that we generate). Without this, I don't get far trying to run the testsuite. With this, on my NixOS system:
```
SUMMARY for test run started at Wed Jun 27 14:01:53 2018 CEST
0:14:32 spent to go through
6445 total tests, which gave rise to
23667 test cases, of which
17325 were skipped
27 had missing libraries
5589 expected passes
92 expected failures
54 caused framework failures
0 caused framework warnings
1 unexpected passes
631 unexpected failures
1 unexpected stat failures
```
=> Fix timeout building rule for Linux

src/Settings/Packages.hs
This addresses #642.
@snowleopard I'm using CabalFlags for now to keep it consistent. I also think it's not necessarily a good idea to throw everything at `GhcCabal Conf` instead, since we do not use ghc-cabal anymore. Since it's at least worth discussing, I just went with uniformity and passed the flags through `CabalFlags`.
=> implement the equivalent of D4955 for hadrian

.travis.yml, appveyor.yml, circle.yml
The fix has landed in GHC HEAD.
Closes #634.
=> Remove the hack to use a patched Cabal submodule in CI

src/Base.hs, src/GHC.hs, src/Rules.hs, src/Rules/Register.hs, src/UserSettings.hs
This does the following:
* Fix the top-level targets, which appear to have been restricted to Stage1 targets only in #531.
* Restore the `stage1Only` logic, remove outdated comments.
* Build `touchy` in Stage1, as requested in #653.
* Move `ghcTags` and `haddock` packages to Stage2, as in the Make build system (#540).
* Keep only Stage0 and Stage1 package databases (we do not need Stage2/Stage3 package databases).
=> Fix defaut top level targets

cfg/system.config.in, doc/user-settings.md, src/Builder.hs, src/CommandLine.hs, src/GHC.hs, src/Oracles/Setting.hs, src/Settings.hs, src/Settings/Builders/Make.hs, src/Settings/Builders/RunTest.hs, src/Settings/Packages.hs
#531 removed install rules (`src/Rules/Install.hs`), but left a lot of supporting code that is now unused.
Hopefully, this clean up completes the removal of install rules. If they are ever coming back to Hadrian in any shape, some useful code can be recovered here.
See #540.
=> Clean up remaining bits of the install rule

src/Builder.hs, src/Packages.hs, src/Rules/BinaryDist.hs, src/Rules/Test.hs
I noticed that the Make build systems builds `runghc` instead of `runhaskell`, so I did the renaming.
This seems to also remove a couple of hacks from Hadrian.
@alpmestan This touches the testsuite and bindist slightly, so please have a look if I'm doing the right thing.
=> Build runghc instead of runhaskell

src/Rules/Test.hs, src/Settings/Builders/RunTest.hs, src/Settings/Default.hs
The driver was invoked with invalid syntax for some arguments, we were not
making sure hsc2hs is built before we run the tests (it's needed by many), etc.
This kills about ~500 unexpected failures.
=> address some issues with the testsuite rules

hadrian.cabal, src/Settings/Flavours/Common.hs, src/Settings/Flavours/Profiled.hs, src/Settings/Flavours/Quick.hs, src/Settings/Flavours/QuickCross.hs, src/Settings/Flavours/Quickest.hs
The only flavours that need the workaround are the ones that build
GHC/{Natural, Num}.hs with -O0, namely 'quick', 'quickest' and 'prof'.
This patches defines the necessary arguments in one place and uses them
in all the aforementionned flavour definitions.
This will allow us to have both quick/quickest/prof builds that come through
as well as an efficient compiler when we want it (with e.g perf), which wasn't
the case before my series of patches for this problem.
=> Work around the "can't use natural in base" problem on a per-flavour basis

src/Settings/Default.hs, src/Settings/Packages.hs
This commit also removes some leftover from my previous PR, sorry about that.
=> Make the test rule depend on ghc-compact, to make this library's tests pass

src/Rules/Clean.hs
Otherwise you get a failure that it can't delete the `.shake.lock` file since Shake has it open.
=> Fix clean so it works on Windows

stack.yaml
At least compiles Hadrian itself, so this seems like a much better prospect - as it is Hadrian is close to getting outside the GHC support Window of last 2 versions.
=> Move to GHC 8.4.3 by upgrading the Stackage snapshot

src/Settings/Packages.hs
This among other things has the effect of giving a correct output for many tests (see RtClosureInspect.hs to see pretty-printing code that's enabled when the integer-gmp flag is enabled (which in turns defines the `INTEGER_GMP` macro)), but is anyway the correct thing to do.
=> set integer-gmp flag when appropriate, when building the compiler lib

src/Rules/Library.hs
It's the obvious error that we've made a few times already. "way == something" instead of "way contains ...".
This was causing linker errors and what not for several tests, which are now fixed, with this patch.
=> fix a logic error that kept us from building/linking object files for many ways

.travis.yml, circle.yml
https://phabricator.haskell.org/D5138
Future CI runs (including the ones for this patch, hopefully) should just work again since the `findPtr` fix landed in master.
=> OS X CI scripts: don't use my GHC branch anymore, D5138 has been merged

src/Hadrian/Oracles/Cabal/Rules.hs, src/Hadrian/Oracles/TextFile.hs
As discussed in #550, we can remove some unnecessary occurrences of `newCache`.
=> Simplify oracles

src/Settings/Packages.hs
This goes hand in hand with https://phabricator.haskell.org/D5146
I'm trying to get the `findPtr` fix landed in master so that we can switch CI back to whatever GHC HEAD is. This way, we could even wait for D5146 to be merged before re-running CI for this patch and making sure that nothing is broken, if we so desire.
We could have a shorter term hack of just passing -threaded ourself explicitly in the right place, but it's a lot hackier and I suspect the diff will not take months to be merged.
This should in theory fix the failure of T8242 (when testing a GHC built by hadrian of course):
``` sh
$ "/home/alp/WT/ghc-hadrian/_tmp/stage1/bin/ghc" T8242.hs -dcore-lint -dcmm-lint -no-user-package-db -rtsopts -fno-warn-missed-specialisations -fshow-warning-groups -fdiagnostics-color=never …
```
=> pass 'threaded' flag for the GHC executable, to link against the threaded RTS

.travis.yml
I saw that (nightly) travis builds are failing because we now only support 8.4 or higher to boot a GHC HEAD build. I don't know how to achieve this for the OS X section though.
Let's see how the linux ones go in the meantime.
=> update GHC versions used on travis
